- hosts: all
  become: yes

  tasks:
    - name: Adding APT repository
    apt_repository:
      repo: deb  https://artifacts.elastic.co/packages/7.x/apt  stable main
      state: present
    # Installing Logstash
    - name: Update repositories cache and install Logstash
      apt:
      name: logstash
      update_cache: yes

    # Enable Logstash service
    - name: Enable Logstash service
      systemd:
        name: logstash
        enabled: yes
    # Start Logstash service
    - name: Start Logstash service
      systemd:
        name: logstash
        state: started
        daemon_reload: yes

