- hosts: localhost
  become: yes
  tasks:
    - name: Copy SSH key from AWS Secrets
      include_tasks: ssh.yml

- hosts: logstash_server
  become: yes
  tasks:
    - name: Launch Logstash Playbook
      include_tasks: logstash.yml

- hosts: elasticsearch_server
  become: yes
  tasks:
    - name: Launch Elasticsearch Playbook
      include_tasks: elasticsearch.yml