name: deploy ansible

on: [push]

jobs:
  ansible-deployment:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::463702550967:role/github-actions-oidc
          aws-region: "eu-central-1"

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          directory: ./
          options: |
            --verbose

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: checkout repo
#       uses: actions/checkout@v2
#     - name: Lint Ansible Playbook
#       uses: ansible/ansible-lint-action@wip/v6
#       with:
#         targets: ""
#   deployAnsible:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#       with: 
#         playbook: ../actions/playbook.yml
        

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Important: This sets up your GITHUB_WORKSPACE environment variable
#       - uses: actions/checkout@v2

#       - name: Run ansible-lint
#         # replace `main` with any valid ref, or tags like `v6`
#         uses: ansible-community/ansible-lint-action@wip/v6
#         # optional:
#         with:
#           path: "playbooks/"  # <-- only one value is allowed