name: deploy ansible

on: [push]

- name: Run playbook
  uses: dawidd6/action-ansible-playbook@v2
  with:
    # Required, playbook filepath
    playbook: playbook.yml
    # Optional, directory where playbooks live
    directory: ../actions
    options: |
      --verbose

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: checkout repo
#       uses: actions/checkout@v2
#     - name: Lint Ansible Playbook
#       uses: ansible/ansible-lint-action@wip/v6
#       with:
#         targets: ""
#   deployAnsible:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#       with: 
#         playbook: ../actions/playbook.yml
        

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Important: This sets up your GITHUB_WORKSPACE environment variable
#       - uses: actions/checkout@v2

#       - name: Run ansible-lint
#         # replace `main` with any valid ref, or tags like `v6`
#         uses: ansible-community/ansible-lint-action@wip/v6
#         # optional:
#         with:
#           path: "playbooks/"  # <-- only one value is allowed