name: deploy ansible

on: [push]

jobs:
  ansible-deployment:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Clone/Checkout your repository code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::463702550967:role/github-actions-oidc
          aws-region: "eu-central-1"

      # - name: Run playbook
      #   run: ls ../../_actions/dawidd6/action-ansible-playbook -al
        
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          directory: ./ansible
          options: |
            --verbose
